services:
  seobom-backend-prod:
    container_name: seobom-backend-prod
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: seobom-backend:latest
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /var/log/seobom-prod:/apps/logs
    networks:
      - deploy
    restart: always

  nginx-prod:
    container_name: nginx-prod
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - ../nginx/conf.d/prod:/etc/nginx/conf.d:ro
    depends_on:
      - seobom-backend-prod
    networks:
      - deploy
    restart: always

  certbot-prod:
    container_name: certbot-prod
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew --webroot -w /var/www/certbot;
               sleep 12h & wait $${!};
             done"
    networks:
      - deploy
    restart: always

networks:
  deploy:
    external: true