services:
  seobom-backend-test:
    container_name: seobom-backend-test
    image: seobom-backend-test:latest
    expose:
      - "8080" # 내부망 통신만 허용
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - /var/log/seobom:/apps/logs
    networks:
      - deploy
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew --webroot -w /var/www/certbot;
               sleep 12h & wait $${!};
             done"
    networks:
      - deploy
    restart: always

networks:
  deploy:
    external: true