services:
  seobom-backend-test:
    container_name: seobom-backend-test
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: seobom-backend:latest
    expose:
      - "8080" # 내부망 통신만 허용
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - /var/log/seobom-test:/apps/logs
    networks:
      - deploy
    restart: always

  nginx-test:
    container_name: nginx-test
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro   # SSL 인증서 공유
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - ../nginx/conf.d/test:/etc/nginx/conf.d:ro
    depends_on:
      - seobom-backend-test
    networks:
      - deploy
    restart: always

  certbot-test:
    container_name: certbot-test
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew --webroot -w /var/www/certbot;
               sleep 12h & wait $${!};
             done"
    networks:
      - deploy
    restart: always

networks:
  deploy:
    external: true